CREATE TABLE DEPOSIT(

ACTNO INT,
CNAME VARCHAR(50),
BNAME VARCHAR(50), 
AMOUNT DECIMAL(8,2),
ADATE DATETIME
);

INSERT INTO DEPOSIT
VALUES(101, 'MEET', 'MAVDI', 10000, '1-3-2025' ),
(102, 'JAY', 'MADHAPAR', 5000, '4-1-2026' ),
(103, 'RAHUL', 'BEDI', 3500, '7-1-2026' ),
(104, 'RIYA', 'MAVDI', 1200, '7-6-2025' ),
(105, 'MANSI', 'KKV HALL', 3000, '2-3-2024'),
(106, 'DIYA', 'MADHAPAR', 2000, '1-3-2025' ),
(107, 'MIRAL', 'BEDI', 1000, '5-9-2025' ),
(108, 'UDAY', 'UMIYA CHOWK', 5000, '2-7-2025' ),
(109, 'CHARMI', 'SHITAL PARK', 7000, '2-8-2026'),
(110, 'BHAVIN', 'RING ROAD', 8000, '2-2-2025' ),
(111, 'BANSI', NULL, 9000, '1-1-2025' )

SELECT * FROM DEPOSIT

--From the table DEPOSIT perform the following queries:  
--Part – A:  
--1. Copy all records from DEPOSIT where AMOUNT > 3000 into HIGH_AMOUNT.
SELECT *
INTO HIGH_AMOUNT
FROM DEPOSIT
WHERE AMOUNT > 3000

--2. Copy only CNAME and AMOUNT from DEPOSIT where BNAME = 'MAVDI' into MAVDI_CUSTOMERS.
SELECT CNAME, AMOUNT
INTO MAVDI_CUSTOMERS
FROM DEPOSIT
WHERE BNAME = 'MAVDI'

--3. Copy records of DEPOSIT where ADATE > '2025-01-01' into RECENT_DEPOSITS.
SELECT *
INTO RECENT_DEPOSITS
FROM DEPOSIT
WHERE ADATE > '2025-01-01'

--4. Copy distinct BNAME from DEPOSIT into BRANCH_LIST.
SELECT BNAME
INTO BRANCH_LIST
FROM DEPOSIT

--5. Copy top 5 records from DEPOSIT into TOP_DEPOSITS.
SELECT TOP 5 *
INTO TOP_DEPOSITS
FROM DEPOSIT

--6. Copy records where AMOUNT between 2000 and 6000 into MID_RANGE.
SELECT *
INTO MID_RANGE
FROM DEPOSIT
WHERE AMOUNT BETWEEN 2000 AND 6000

--7. Copy distinct branch names from DEPOSIT into UNIQUE_BRANCH.
SELECT DISTINCT BNAME
INTO UNIQUE_BRANCH
FROM DEPOSIT

--8. Copy records with NULL branch into NO_BRANCH_ASSIGNED.
SELECT *
INTO NO_BRANCH_ASSIGNED
FROM DEPOSIT
WHERE BNAME IS NULL

--9. Copy all records and rename AMOUNT as BALANCE into DEPOSIT_COPY.
SELECT ACTNO, CNAME, BNAME, AMOUNT AS BALANCE, ADATE
INTO DEPOSIT_COPY
FROM DEPOSIT

--10. Copy records where BNAME in ('MAVDI','BEDI') into SELECTED_BRANCH.
SELECT *
INTO SELECTED_BRANCH
FROM DEPOSIT
WHERE BNAME IN ('MAVDI','BEDI')

---------------------------------------------------------------------------

CREATE TABLE STUDENT(

STDID INT,
SNAME VARCHAR(50),
CITY VARCHAR(50),
SPI DECIMAL(4,2),
BRANCH VARCHAR(50)

);

INSERT INTO STUDENT
VALUES(101, 'HETVI', 'RAJKOT', 7.40, 'COMPUTER'),
(102, 'RAJ', 'MORBI', 9.50, 'MECHANICAL'),
(103, 'VISHAL', 'RAJKOT', 9.00, 'CIVIL'),
(104, 'DEEP', 'SURAT', 8.80, 'COMPUTER'),
(105, 'DHARMIK', 'BARODA', 8.80, 'CHEMICAL'),
(106, 'KRUNAL', 'VAPI', 9.00, 'CIVIL'),
(107, 'RIYA', 'NAVSARI', 5.50, 'COMPUTER'),
(108, 'VRUNDA', 'KUTCH', 7.60, 'ELECTRICAL'),
(109, 'SMAIR', 'JAMNAGAR', 6.80, 'EC'),
(110, 'PARAG', 'SURAT', 7.00, 'CHEMICAL'),
(111, 'HARSH', 'RAJKOT', 4.00, NULL)

SELECT * FROM STUDENT


--From the table Student perform the following queries:  
--Part – B:  
--11. Create a new table STUDENT_BACKUP from STUDENT without copying any data.
SELECT *
INTO STUDENT_BACKUP
FROM STUDENT
WHERE 3 = 9

--12. Copy SNAME and CITY where BRANCH = 'COMPUTER' into CS_STUDENTS.
SELECT SNAME, CITY
INTO CS_STUDENTS
FROM STUDENT
WHERE BRANCH = 'COMPUTER'

--13. Copy top 3 students based on SPI into TOPPER_LIST.
SELECT TOP 3 *
INTO TOPPER_LIST
FROM STUDENT
WHERE BRANCH = 'COMPUTER'
ORDER BY SPI DESC

--14. Copy distinct CITY from STUDENT into CITY_LIST.
SELECT DISTINCT CITY
INTO CITY_LIST
FROM STUDENT

--15. Copy records where STDID between 103 and 108 into MID_STUDENTS.
SELECT SNAME, CITY
INTO MID_STUDENTS
FROM STUDENT
WHERE STDID BETWEEN 103 AND 108

SELECT * FROM STUDENT
--From the table Student perform the following queries:  
--Part – C:  
--16. Copy records with NULL branch into NULL_BRANCH_STUDENTS.
SELECT *
INTO NULL_BRANCH_STUDENTS
FROM STUDENT
WHERE BRANCH IS NULL

--17. Copy all STUDENT records and rename SPI as PERFORMANCE into STUDENT_COPY.
SELECT STDID, SNAME, CITY, SPI AS PERFORMANCE, BRANCH
INTO STUDENT_COPY
FROM STUDENT

--18. Copy records where CITY in ('RAJKOT','SURAT') into CITY_WISE.
SELECT *
INTO CITY_WISE
FROM STUDENT
WHERE CITY IN ('RAJKOT','SURAT')

--19. Copy students where BRANCH <> 'CIVIL' into NON_CIVIL_STUDENTS.
SELECT *
INTO NON_CIVIL_STUDENTS
FROM STUDENT
WHERE BRANCH <> 'CIVIL'

--20. Copy selected columns (SNAME, CITY) from STUDENT table into a new table.
SELECT SNAME, CITY
INTO NEW_TAB
FROM STUDENT
